### ISSUE TITLE
Audio hängt hinterher

### ISSUE THREAD

**Issue by pquerner** [rols1/Plex-Plugin-ARDMediathek2016#2]
Bei mir kommt es im Google Chrome (andere Browser ungetestet) zu einem hängen der Audiospur. Audio und Bild sind nicht synchron.

Google Chrome Version 63.0.3239.84 (Offizieller Build) (64-Bit)
Plex Version 3.27.1
Plugin: 3.3.6 11d1a88

**Comment by rols1** [comment]
Darauf kann ich mir noch keinen Reim machen. Im Plugin werden die Video- und Audiodaten nicht getrennt verarbeitet - auch nicht per Parameter beeinflusst.
Kann das Problem ev. eingegrenzt werden? Verhalten bei TVLive / Sendung, Verhalten in anderen Plugins? Tritt das Phänomen sporadisch oder dauerhaft auf?

**Comment by rols1** [comment]
ich habe meinen Browser auf dieselbe Version upgedated (bisher noch 62er)  und nochmal gestestet.
Mit Plexserver Version 1.9.6.4429 und dem integrierten  Web Player Version 3.23.1 habe ich auch einen heftigen Audio/Bild-Versatz 
**Mit dem externen  Web Player Version 3.23.1  (https://app.plex.tv/web/app) tritt das Problem nicht auf.**
Inwieweit die Version  des Google Chrome eine Rolle spielt, kann ich leider nicht mehr sagen - den integrierten  Web Player habe ich vor dem heutigen Update nicht im alten Browser getestet.

**Comment by rols1** [comment]
Es gibt weitere Probleme mit Plex. Habe soeben die neue Server-Version plexmediaserver-1.10.0.4523-648bc61d4.x86_64.rpm installiert. Damit wird alles transkodiert, auch die vom Plugin angebotenen festen Bandbreiten/Auflösungen. 
Das ist praktisch bei mir nicht nutzbar, da der Transcoder den PC stark auslastet.
Ich habe wieder meinen alten Web Player installiert (Version  2.7.0) - der funktioniert immer noch bestens.
Bei Interesse: Download https://c.gmx.net/@327723216099344844/cASZJUNuQpqlEImIS62dmA, Anleitung https://forums.plex.tv/discussion/comment/1457027/#Comment_1457027 (englisch).
